const TYPES=['No usa cinturón de seguridad','No usa EPP','Uso de distractores','Incumplimiento de procedimiento','Exceso de velocidad','Maniobra insegura','Uso inadecuado de equipos/herramientas','Orden y limpieza','Almacenamiento / apilamiento inseguro','Ergonomía / postura','Otros'];
const $=s=>document.querySelector(s); let records=JSON.parse(localStorage.getItem('sst-ventanilla-records')||'[]'); let active=records;
const canCloseObservations=()=>{try{return JSON.parse(sessionStorage.getItem('sst-offline-user')||'{}').role==='ADMINISTRADOR'}catch{return false}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function populate(){['#formType','#filterType'].forEach(id=>$(id).insertAdjacentHTML('beforeend',TYPES.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('')));$('#observationForm [name=date]').value=new Date().toISOString().slice(0,10)}
function save(){localStorage.setItem('sst-ventanilla-records',JSON.stringify(records))}function show(screen){$('#viewerScreen').hidden=screen!=='viewer';$('#formScreen').hidden=screen!=='form';$('#viewerNav').classList.toggle('active',screen==='viewer');$('#registerNav').classList.toggle('active',screen==='form');window.scrollTo(0,0)}
function badge(status){return `<span class="badge ${status.replace(' ','-')}">${status}</span>`}function render(){const c=records.reduce((a,r)=>(a[r.status]++,a),{Pendiente:0,'En proceso':0,Cerrada:0});$('#totalMetric').textContent=records.length;$('#pendingMetric').textContent=c.Pendiente;$('#progressMetric').textContent=c['En proceso'];$('#closedMetric').textContent=c.Cerrada;$('#resultsCount').textContent=`${active.length} resultado${active.length===1?'':'s'}`;$('#cards').innerHTML=active.map(r=>`<article class="card"><div class="card-top"><div><h3>${esc(r.workerName)}</h3><div class="meta">${esc(r.id)} · ${esc(r.date)} · ${esc(r.area)}</div></div>${badge(r.status)}</div><div class="type">${esc(r.type)}</div><p>${esc(r.observation)}</p><p><strong>Acción:</strong> ${esc(r.action)}</p><p><strong>Responsable:</strong> ${esc(r.responsible)} · <strong>Límite:</strong> ${esc(r.dueDate)}</p><footer><button class="button secondary" data-view="${r.id}">Ver hallazgo</button><button class="button ${r.closure?'secondary':'primary'}" data-close="${r.id}">${r.closure?'Ver cierre':r.status==='Cerrada'?'Ver cierre':'Gestionar cierre'}</button></footer></article>`).join('');$('#emptyState').hidden=active.length>0;}
function filters(){const v=id=>$(id).value.trim().toLowerCase();active=records.filter(r=>(!v('#filterName')||r.workerName.toLowerCase().includes(v('#filterName')))&&(!v('#filterDni')||r.dni.includes(v('#filterDni')))&&(!v('#filterPlate')||r.plate.toLowerCase().includes(v('#filterPlate')))&&(!v('#filterFrom')||r.date>=v('#filterFrom'))&&(!v('#filterTo')||r.date<=v('#filterTo'))&&(!v('#filterSite')||r.site===$('#filterSite').value)&&(!v('#filterType')||r.type===$('#filterType').value)&&(!v('#filterStatus')||r.status===$('#filterStatus').value));render()}
function evidence(files){return Promise.all([...files].map(f=>new Promise((resolve,reject)=>{if(f.size>5*1024*1024)return reject(new Error(`${f.name} supera los 5 MB`));let fr=new FileReader;fr.onload=()=>resolve({name:f.name,type:f.type,data:fr.result});fr.onerror=reject;fr.readAsDataURL(f)})))}
function fileHTML(list=[]){return list.length?`<div class="evidence">${list.map(f=>f.type.startsWith('image/')?`<a href="${f.data}" target="_blank"><img src="${f.data}" alt="${esc(f.name)}"></a>`:`<a href="${f.data}" download="${esc(f.name)}">📎 ${esc(f.name)}</a>`).join('')}</div>`:'Sin evidencia adjunta'}
function openDetail(id,closing=false){let r=records.find(x=>x.id===id);let fields=closing?[['Fecha de cierre',r.closure?.date||'Sin cierre'],['Usuario que cerró',r.closure?.user||'—'],['Comentario de cierre',r.closure?.comment||'—'],['Evidencia de cierre',fileHTML(r.closure?.evidence),'full']]:[['ID',r.id],['Estado',r.status],['Nombre del trabajador',r.workerName],['DNI',r.dni],['Placa',r.plate||'—'],['Fecha de observación',r.date],['Sede',r.site],['Área / puesto',r.area],['Tipo de observación',r.type],['Observación',r.observation,'full'],['Acción a tomar',r.action,'full'],['Responsable',r.responsible],['Fecha límite',r.dueDate],['Registrado por',r.registeredBy],['Fecha y hora de registro',new Date(r.createdAt).toLocaleString('es-PE')],['Evidencia',fileHTML(r.evidence),'full']];$('#dialogContent').innerHTML=`<div class="dialog-body"><div class="dialog-head"><div><p class="eyebrow">${closing?'CIERRE DE OBSERVACIÓN':'HALLAZGO'}</p><h2>${esc(r.workerName)}</h2></div><button class="close" onclick="detailDialog.close()">×</button></div><div class="details">${fields.map(([a,b,cl])=>`<div class="${cl||''}"><span>${a}</span>${b}</div>`).join('')}</div>${!closing&&!r.closure?`<div class="state-actions">${r.status==='Pendiente'?`<button class="button secondary" onclick="setProgress('${r.id}')">Pasar a En proceso</button>`:''}<button class="button primary" onclick="closeForm('${r.id}')">Cerrar observación</button></div>`:''}</div>`;$('#detailDialog').showModal()}
window.setProgress=id=>{let r=records.find(x=>x.id===id);r.status='En proceso';save();filters();openDetail(id);toast('Observación marcada como En proceso')};window.closeForm=id=>{$('#dialogContent').innerHTML=`<div class="dialog-body"><div class="dialog-head"><div><p class="eyebrow">CIERRE</p><h2>Completar observación</h2></div><button class="close" onclick="detailDialog.close()">×</button></div><form id="closeForm" class="form-grid"><label>Fecha de cierre *<input name="date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Usuario que realizó el cierre *<input name="user" required></label><label class="wide">Comentario de cierre *<textarea name="comment" required></textarea></label><label class="wide file-label">Evidencia de cierre<input name="evidence" type="file" accept="image/*,.pdf,.doc,.docx" multiple></label><div class="form-actions wide"><button type="button" class="button secondary" onclick="openDetail('${id}')">Cancelar</button><button class="button primary">Guardar cierre</button></div></form></div>`;$('#closeForm').onsubmit=async e=>{e.preventDefault();let d=new FormData(e.target);try{let r=records.find(x=>x.id===id);r.status='Cerrada';r.closure={date:d.get('date'),user:d.get('user'),comment:d.get('comment'),evidence:await evidence(d.getAll('evidence').filter(f=>f.size))};save();filters();detailDialog.close();toast('Observación cerrada correctamente')}catch(err){toast(err.message)}}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function exportExcel(){let headers=['ID','Nombre del trabajador','DNI','Placa','Fecha','Sede','Área / puesto','Tipo de observación','Observación','Acción a tomar','Evidencia','Responsable','Fecha límite de cierre','Estado','Fecha de cierre','Usuario que registró','Fecha y hora de registro'];let rows=records.map(r=>[r.id,r.workerName,r.dni,r.plate,r.date,r.site,r.area,r.type,r.observation,r.action,(r.evidence||[]).map(x=>x.name).join(', '),r.responsible,r.dueDate,r.status,r.closure?.date||'',r.registeredBy,new Date(r.createdAt).toLocaleString('es-PE')]);let html=`<table><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr>${rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</table>`;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel'}));a.download='observaciones-sst-ventanilla.xls';a.click();URL.revokeObjectURL(a.href)}
populate();render();$('#viewerNav').onclick=()=>show('viewer');$('#registerNav').onclick=()=>show('form');$('#emptyRegister').onclick=()=>show('form');$('#backToViewer').onclick=()=>show('viewer');$('#cancelForm').onclick=()=>show('viewer');$('#searchBtn').onclick=filters;$('#clearFilters').onclick=()=>{document.querySelectorAll('.filters input,.filters select').forEach(x=>x.value='');active=records;render()};$('#exportBtn').onclick=exportExcel;$('#cards').onclick=e=>{let id=e.target.dataset.view||e.target.dataset.close;if(!id)return;let r=records.find(x=>x.id===id);openDetail(id,!!e.target.dataset.close&&!!r.closure)};$('#observationForm').onsubmit=async e=>{e.preventDefault();let d=new FormData(e.target);try{let files=d.getAll('evidence').filter(f=>f.size);let r=Object.fromEntries([...d.entries()].filter(([k,v])=>k!=='evidence'));r.id='SST-VEN-'+Date.now().toString().slice(-7);r.status='Pendiente';r.createdAt=new Date().toISOString();r.registeredBy='Usuario local';r.evidence=await evidence(files);records.unshift(r);save();active=records;render();e.target.reset();$('#observationForm [name=date]').value=new Date().toISOString().slice(0,10);show('viewer');toast('Observación registrada correctamente')}catch(err){toast(err.message)}};

// Solo el administrador puede gestionar o confirmar el cierre de una observación.
const renderBase=render;render=function(){renderBase();if(!canCloseObservations())document.querySelectorAll('[data-close]').forEach(button=>{const record=records.find(row=>row.id===button.dataset.close);if(!record?.closure&&record?.status!=='Cerrada')button.remove()})};
const openDetailBase=openDetail;openDetail=function(id,closing=false){openDetailBase(id,closing);if(!canCloseObservations())document.querySelectorAll('[onclick*="closeForm"],[onclick*="setProgress"]').forEach(button=>button.remove())};
const closeFormBase=window.closeForm;window.closeForm=id=>{if(!canCloseObservations()){toast('Solo el administrador puede cerrar observaciones');return}closeFormBase(id)};
