const OFFLINE=location.protocol==='file:'||location.hostname.endsWith('.workers.dev');const admin={id:'usr_admin_ventanilla_001',dni:'25866034',name:'Milagros Alicia Canchari Martinez',full_name:'Milagros Alicia Canchari Martinez',role:'ADMINISTRADOR',active:1};
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b)));const hash=async(p,s)=>b64(await crypto.subtle.deriveBits({name:'PBKDF2',salt:Uint8Array.from(atob(s),x=>x.charCodeAt(0)),iterations:600000,hash:'SHA-256'},await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']),256));
const offlineApi=async(p,o={})=>{let method=o.method||'GET',b=o.body?JSON.parse(o.body):{},key='sst-offline-records',users=JSON.parse(localStorage.getItem('sst-offline-users')||'[]'),signed=sessionStorage.getItem('sst-offline-user');if(p==='/api/auth/login'){let match=[admin,...users].find(x=>x.dni===String(b.dni).trim()&&x.full_name.toLowerCase()===String(b.full_name).trim().toLowerCase()&&x.active);if(!match)throw Error('DNI o nombre no autorizado');let logged={id:match.id,dni:match.dni,name:match.full_name,role:match.role};sessionStorage.setItem('sst-offline-user',JSON.stringify(logged));return {user:logged}}if(p==='/api/auth/logout'){sessionStorage.removeItem('sst-offline-user');return null}if(!signed)throw Error('Ingresa tu DNI y nombre completo para continuar');let u=JSON.parse(signed);if(p==='/api/auth/me')return u;if(p==='/api/observations'&&method==='GET')return JSON.parse(localStorage.getItem(key)||'[]');if(p==='/api/observations'&&method==='POST'){let rows=JSON.parse(localStorage.getItem(key)||'[]'),r={...b,id:'SST-VEN-'+Date.now(),site:'Ventanilla',status:'Pendiente',reporter_name:u.name,created_at:new Date().toISOString()};rows.unshift(r);localStorage.setItem(key,JSON.stringify(rows));return {id:r.id}}if(p==='/api/users'&&method==='GET')return [admin,...users];if(p==='/api/users'&&method==='POST'){if(u.role!=='ADMINISTRADOR')throw Error('Sin permisos');if(users.some(x=>x.dni===b.dni))throw Error('DNI ya registrado');users.push({id:crypto.randomUUID(),dni:b.dni,full_name:b.full_name,role:b.role,active:b.active?1:0});localStorage.setItem('sst-offline-users',JSON.stringify(users));return {ok:true}}throw Error('Operación no disponible en modo local')};
const api=async(p,o={})=>{if(OFFLINE)return offlineApi(p,o);const r=await fetch(p,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(o.headers||{})},...o});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.error||'No se pudo completar la operación')}return r.status===204?null:r.json()};
const mapRow=r=>({id:r.id,workerName:r.worker_name,dni:r.worker_dni,personType:r.person_type,plate:r.plate||'',date:r.observation_date,site:r.site,area:r.area,type:r.observation_type,observation:r.observation,action:r.action_to_take,responsible:r.responsible,dueDate:r.due_date,status:r.status,registeredBy:r.reporter_name,createdAt:r.created_at,closure:r.closed_at?{date:r.closure_date,user:r.closed_by_id,comment:r.closure_comment,evidence:[]}:null,evidence:[]});
async function loadProtectedRecords(){const list=await api('/api/observations');records=list.map(mapRow);active=records;render()}
async function session(){try{const u=await api('/api/auth/me');$('#userChip').textContent=`${u.name} · ${u.role}`;$('#loginGate').hidden=true;if(u.role==='CONSULTA')$('#registerNav').hidden=true;await loadProtectedRecords()}catch{$('#loginGate').hidden=false}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{const u=await api('/api/auth/login',{method:'POST',body:JSON.stringify({dni:f.get('dni'),full_name:f.get('fullName')})});$('#userChip').textContent=`${u.user.name} · ${u.user.role}`;$('#loginGate').hidden=true;await loadProtectedRecords()}catch(err){$('#loginError').textContent=err.message}};
$('#logoutBtn').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});records=[];active=[];render();$('#loginForm').reset();$('#loginGate').hidden=false};
$('#observationForm').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target),p={worker_name:d.get('workerName'),worker_dni:d.get('dni'),person_type:d.get('personType'),plate:d.get('plate'),observation_date:d.get('date'),area:d.get('area'),observation_type:d.get('type'),observation:d.get('observation'),action_to_take:d.get('action'),responsible:d.get('responsible'),due_date:d.get('dueDate')};try{await api('/api/observations',{method:'POST',body:JSON.stringify(p)});e.target.reset();$('#observationForm [name=date]').value=new Date().toISOString().slice(0,10);await loadProtectedRecords();show('viewer');toast('Observación registrada correctamente')}catch(err){toast(err.message)}};
window.setProgress=async id=>{try{await api(`/api/observations/${encodeURIComponent(id)}/status`,{method:'POST',body:JSON.stringify({status:'En proceso'})});await loadProtectedRecords();openDetail(id);toast('Observación marcada como En proceso')}catch(err){toast(err.message)}};
$('#exportBtn').onclick=()=>OFFLINE?exportExcel():location.href='/api/export';
function userScreen(show){$('#viewerScreen').hidden=show;$('#formScreen').hidden=true;$('#usersScreen').hidden=!show;window.scrollTo(0,0)}
async function loadUsers(){const users=await api('/api/users');$('#usersTable').innerHTML=`<table><thead><tr><th>DNI</th><th>Nombre completo</th><th>Rol</th><th>Estado</th></tr></thead><tbody>${users.map(u=>`<tr><td>${u.dni}</td><td>${u.full_name||u.name}</td><td>${u.role}</td><td>${u.active?'Activo':'Inactivo'}</td></tr>`).join('')}</tbody></table>`}
$('#usersNav').onclick=async()=>{userScreen(true);try{await loadUsers()}catch(err){toast(err.message)}};$('#usersBack').onclick=()=>userScreen(false);
$('#userForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/users',{method:'POST',body:JSON.stringify({dni:f.get('dni'),full_name:f.get('fullName'),role:f.get('role'),active:f.get('active')==='true'})});e.target.reset();await loadUsers();toast('Persona registrada correctamente')}catch(err){toast(err.message)}};
const priorSession=session;session=async function(){try{const u=await api('/api/auth/me');$('#userChip').textContent=`${u.name} · ${u.role}`;$('#loginGate').hidden=true;if(u.role==='ADMINISTRADOR')$('#usersNav').hidden=false;if(u.role==='CONSULTA')$('#registerNav').hidden=true;await loadProtectedRecords()}catch{$('#loginGate').hidden=false}};session();
